
export enum Symbol {
    yellow = "yellow",
    green = "green",
    blue = "blue",
    red = "red",
    purple = "purple",
    black = "black",
    white = "white",
    success = "success",
    advantage = "advantage",
    triumph = "triumph",
    failure = "failure",
    threat = "threat",
    despair = "despair",
    lightside = "lightside",
    darkside = "darkside",

    "dice/black-" = "dice/black-",
    "dice/black-f" = "dice/black-f",
    "dice/black-t" = "dice/black-t",
    "dice/blue-" = "dice/blue-",
    "dice/blue-a" = "dice/blue-a",
    "dice/blue-aa" = "dice/blue-aa",
    "dice/blue-s" = "dice/blue-s",
    "dice/blue-sa" = "dice/blue-sa",
    "dice/green-" = "dice/green-",
    "dice/green-a" = "dice/green-a",
    "dice/green-aa" = "dice/green-aa",
    "dice/green-s" = "dice/green-s",
    "dice/green-sa" = "dice/green-sa",
    "dice/green-ss" = "dice/green-ss",
    "dice/purple-" = "dice/purple-",
    "dice/purple-f" = "dice/purple-f",
    "dice/purple-ff" = "dice/purple-ff",
    "dice/purple-ft" = "dice/purple-ft",
    "dice/purple-t" = "dice/purple-t",
    "dice/purple-tt" = "dice/purple-tt",
    "dice/red-" = "dice/red-",
    "dice/red-d" = "dice/red-d",
    "dice/red-f" = "dice/red-f",
    "dice/red-ff" = "dice/red-ff",
    "dice/red-ft" = "dice/red-ft",
    "dice/red-t" = "dice/red-t",
    "dice/red-tt" = "dice/red-tt",
    "dice/white-l" = "dice/white-l",
    "dice/white-ll" = "dice/white-ll",
    "dice/white-n" = "dice/white-n",
    "dice/white-nn" = "dice/white-nn",
    "dice/yellow-" = "dice/yellow-",
    "dice/yellow-a" = "dice/yellow-a",
    "dice/yellow-aa" = "dice/yellow-aa",
    "dice/yellow-r" = "dice/yellow-r",
    "dice/yellow-s" = "dice/yellow-s",
    "dice/yellow-sa" = "dice/yellow-sa",
    "dice/yellow-ss" = "dice/yellow-ss"

}